# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://fedeisas.github.io/
baseurl: /
title: Fede Isas
author: Fede Isas
description: Hi! I'm Fede Isas and I'm a programmer. This is my personal contact site.
avatar: profile.png
email: federicoisas@gmail.com
github: fedeisas # username
twitter: fedeisas
linkedin: fedeisas
stackoverflow: users/227927/fedeisas   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-15391010-1

# needed for travis-ci build
exclude: [vendor]

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]